export const enUS = {
  AppBar: {
    cart: 'Cart',
    signOut: 'SignOut',
    signIn: 'SignIn',
    signUp: 'SignUp',
  },
  SignUp: {
    name: 'Name',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm password',
    submit: 'SignUp',
  },
  SignIn: {
    email: 'Email',
    password: 'Password',
    submit: 'SignIn',
  },
  Cart: {
    emptyCart: 'Your cart is empty',
    buyButton: 'Buy',
    totalPrice: 'Total Price',
  },
  PaymentForm: {
    paymentDetails: 'Payment details',
    cardNumber: 'Card number',
    expirationDate: 'Expiration date',
    cvv: 'CVV',
    submit: 'Submit',
  },
  Search: {
    search: 'search',
    selectOption: 'select option',
  },
  MoviePage: {
    submit: 'Submit',
    feedback: 'Give feedback',
    goHome: 'Go home',
    country: 'country',
    duration: 'duration',
    releaseDate: 'release date (year)',
    productionCompanies: 'production companies',
    genres: 'genres',
    categories: 'categories',
    director: 'director',
    actors: 'actors',
    description: 'Description',
  },
  Filtration: {
    genres: 'Genres',
    categories: 'Categories',
    countries: 'Countries',
    voteAverage: 'Vote average',
    year: 'Year',
  },
  authSlice: {
    100: 'processing. Just wait for a while',
    400: 'SignIn, please',
    500: 'Such user already exists',
    error: 'Error',
  },
  cartSlice: {
    noCart: 'No cart for current user exists',
  },
};
