export const ru = {
  AppBar: {
    cart: 'Корзина',
    signOut: 'Выход',
    signIn: 'Вход',
    signUp: 'Регистрация',
  },
  SignUp: {
    name: 'Имя',
    email: 'Эл. почта',
    password: 'Пароль',
    confirmPassword: 'Подтвердите пароль',
    submit: 'Зарегистрироваться',
  },
  SignIn: {
    email: 'Эл. почта',
    password: 'Пароль',
    submit: 'Войти',
  },
  Cart: {
    emptyCart: 'Ваша корзина пуста',
    buyButton: 'Купить',
    totalPrice: 'Итого',
  },
  PaymentForm: {
    paymentDetails: 'Данные карты',
    cardNumber: 'Номер карты',
    expirationDate: 'Срок Действия',
    cvv: 'CVV',
    submit: 'Подтвердить',
  },
  Search: {
    search: 'поиск',
    selectOption: 'поиск по...',
  },
  MoviePage: {
    submit: 'Отправить',
    feedback: 'Написать отзыв',
    goHome: 'Вернуться на главную',
    country: 'страна',
    duration: 'продолжительность',
    releaseDate: 'год',
    productionCompanies: 'кинокомпания',
    genres: 'жанр',
    categories: 'категория',
    director: 'режиссёр',
    actors: 'в ролях',
    description: 'Описание',
  },
  Filtration: {
    genres: 'Жанры',
    categories: 'Категории',
    countries: 'Страны',
    voteAverage: 'Средняя оценка',
    year: 'Год',
  },
  AuthStatuses: {
    100: 'идет обработка. Ожидайте',
    400: 'Залогинтесь, пожалуйста',
    500: 'Данный пользователь уже существует',
    error: 'Ошибка',
  },
  CartStatuses: {
    noCart: 'Корзины для данного пользователя не существует',
  },
};
