export const en = {
  AppBar: {
    cart: 'Cart',
    signOut: 'SignOut',
    signIn: 'SignIn',
    signUp: 'SignUp',
  },
  SignUp: {
    name: 'Name',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm password',
    submit: 'SignUp',
  },
  SignIn: {
    email: 'Email',
    password: 'Password',
    submit: 'SignIn',
  },
  Cart: {
    emptyCart: 'Your cart is empty',
    buyButton: 'Buy',
    totalPrice: 'Total Price',
  },
  PaymentForm: {
    paymentDetails: 'Payment details',
    cardNumber: 'Card number',
    expirationDate: 'Expiration date',
    cvv: 'CVV',
    submit: 'Submit',
  },
  Search: {
    search: 'search',
    selectOption: 'select option',
  },
  MoviePage: {
    submit: 'Submit',
    feedback: 'Give feedback',
    goHome: 'Go home',
    country: 'country',
    duration: 'duration',
    releaseDate: 'release date (year)',
    productionCompanies: 'production companies',
    genres: 'genres',
    categories: 'categories',
    director: 'director',
    actors: 'actors',
    description: 'Description',
    min: 'min',
  },
  Filtration: {
    genres: 'Genres',
    categories: 'Categories',
    countries: 'Countries',
    voteAverage: 'Vote average',
    year: 'Year',
    Action: 'Action',
    Comedy: 'Comedy',
    Fantasy: 'Fantasy',
    Thriller: 'Thriller',
    Horror: 'Horror',
    Crime: 'Crime',
    Drama: 'Drama',
    Movie: 'Movie',
    Cartoon: 'Cartoon',
    USA: 'USA',
    German: 'German',
    France: 'France',
    Canada: 'Canada',
  },
  AuthStatuses: {
    '100': 'processing. Just wait for a while',
    '400': 'SignIn, please',
    '500': 'Such user already exists',
    error: 'Error',
  },
  CartStatuses: {
    'Cart error': 'Something went wrong in cart',
    noCart: 'No cart for current user exists',
  },
  ErrorStatuses: {
    Error: 'Error occured',
    'Try again': 'Try again',
    'Try again later': 'Try again later',
    'Go to login page': 'Go to login page',
    '401': 'You are not authorized',
    '403': 'You do not have permission to access this resource',

    'Error in /cart': 'Error in Cart',
    'Network Error in /cart': 'Network Error in Cart',
    'Network Error in /cart. Please try later': 'Network Error in Cart. Please try later',
    '400 in /cart': '400. Bad request in Cart',
    '401 in /cart': 'You are not authorized',
    '403 in /cart': 'You do not have permission to access this resource',
    '404 in /cart': '404. This request does not exist in Cart',
    '500 in /cart': '500. Internal server error. No cart for current user exists',
    '502 in /cart': '502. Bad gateway in Cart',
    '503 in /cart': '503. Service Unavailable in Cart',

    'Error in /user/4': 'Error in My Movies',
    'Network Error in /user/4': 'Network Error in My Movies',
    'Network Error in /user/4. Please try later': 'Network Error in My Movies. Please try later',
    '400 in /user/4': '400. Bad request in My Movies',
    '401 in /user/4': 'You are not authorized',
    '403 in /user/4': 'You do not have permission to access this resource',
    '404 in /user/4': '404. This request does not exist in My Movies',
    '500 in /user/4': '500. Internal server error. My Movies does not exist for current user',
    '502 in /user/4': '502. Bad gateway in My Movies',
    '503 in /user/4': '503. Service Unavailable in My Movies',
  },
  UserMenu: {
    adminPanel: 'Admin panel',
    profile: 'Profile',
    orders: 'Orders',
    favorites: 'Favorites',
    feedback: 'My feedback',
    myMovies: 'My movies',
    signout: 'Sign Out',
  },
  AdminPanel: {
    adminPanel: 'Admin panel',
    enterMovieTitle: 'Enter movie title',
    enterUserEmail: 'Enter user email',
    addMovie: 'Add movie',
    allUsers: 'All users',
    allMovies: 'All movies',
    siteSettings: 'Site settings',
  },
  mockFavorites: {
    favoritesPage: 'Favorites page',
    goBack: 'GO BACK',
  },
  mockOrders: {
    orderPage: 'Order page',
    goBack: 'GO BACK',
  },
  mockProfile: {
    profilePage: 'Profile page',
    goBack: 'GO BACK',
  },
  ModalAddMovieToCart: {
    selectPeriod: 'Select subscription period',
    selectFormat: 'Select movie format',
    submit: 'Submit',
    forever: 'Forever',
    'for 7 days': 'For 7 days',
    'for 30 days': 'For 30 days',
  },
  UserPage: {
    Profile: 'Profile',
    Favorites: 'Favorites',
    'Orders list': 'Orders list',
    'My feedback': 'My feedback',
    MyMovies: 'My Movies',
    emptyMyMovies: 'You do not have active films',
    save: 'Save',
    name: 'name',
    email: 'email',
    'date of birth': 'date of birth',
    goHome: 'GO HOME',
    empty: 'You favorites are empty!',
    Available: 'Available',
    days: 'd',
    hours: 'h',
    minutes: 'm',
    forever: 'Forever',
  },
  MovieControl: {
    tooltipText: 'This movie is already in your orders',
  },
  myOrders: {
    orders: 'My orders',
    orderId: 'Order ID',
    orderDate: 'Order date',
    filmPrice: 'Film price',
    orderPrice: 'Order price',
  },
};
