export const ru = {
  AppBar: {
    cart: 'Корзина',
    signOut: 'Выход',
    signIn: 'Вход',
    signUp: 'Регистрация',
  },
  SignUp: {
    name: 'Имя',
    email: 'Эл. почта',
    password: 'Пароль',
    confirmPassword: 'Подтвердите пароль',
    submit: 'Зарегистрироваться',
  },
  SignIn: {
    email: 'Эл. почта',
    password: 'Пароль',
    submit: 'Войти',
  },
  Cart: {
    emptyCart: 'Ваша корзина пуста',
    buyButton: 'Купить',
    totalPrice: 'Итого',
  },
  PaymentForm: {
    paymentDetails: 'Данные карты',
    cardNumber: 'Номер карты',
    expirationDate: 'Срок Действия',
    cvv: 'CVV',
    submit: 'Подтвердить',
  },
  Search: {
    search: 'поиск',
    selectOption: 'поиск по...',
  },
  MoviePage: {
    submit: 'Отправить',
    feedback: 'Написать отзыв',
    goHome: 'Вернуться на главную',
    country: 'страна',
    duration: 'продолжительность',
    releaseDate: 'год',
    productionCompanies: 'кинокомпания',
    genres: 'жанр',
    categories: 'категория',
    director: 'режиссёр',
    actors: 'в ролях',
    description: 'Описание',
    min: 'мин',
  },
  Filtration: {
    genres: 'Жанры',
    categories: 'Категории',
    countries: 'Страны',
    voteAverage: 'Средняя оценка',
    year: 'Год',
    Action: 'Боевик',
    Comedy: 'Комедия',
    Fantasy: 'Фантастика',
    Thriller: 'Триллер',
    Horror: 'Ужасы',
    Crime: 'Криминал',
    Drama: 'Драма',
    Movie: 'Фильм',
    Cartoon: 'Мультфильм',
    USA: 'США',
    German: 'Германия',
    France: 'Франция',
    Canada: 'Канада',
  },
  AuthStatuses: {
    '100': 'идет обработка. Ожидайте',
    '400': 'Залогинтесь, пожалуйста',
    '500': 'Данный пользователь уже существует',
    error: 'Ошибка',
  },
  CartStatuses: {
    'Cart error': 'Произошла ошибка при загрузке корзины',
    noCart: 'Корзины для данного пользователя не существует',
  },
  ErrorStatuses: {
    Error: 'Произошла ошибка',
    'Try again': 'Попробуйте снова',
    'Try again later': 'Попробуйте снова позже',
    'Go to login page': 'Вернутся на страницу логина',
    '401': 'Вы не авторизованны',
    '403': 'У вас нет прав для доступа к данному ресурсу',

    'Error in /cart': 'Ошибка при загрузке корзины',
    'Network Error in /cart': 'Ошибка сети при загрузке корзины',
    'Network Error in /cart. Please try later':
      'Ошибка сети при загрузке корзины. Попробуйте снова позже',
    '400 in /cart': '400. Плохой запрос при загрузке корзины',
    '401 in /cart': 'Вы не авторизованны',
    '403 in /cart': 'У вас нет прав для доступа к данному ресурсу',
    '404 in /cart': '404. Данный запрос не существует в корзине',
    '500 in /cart':
      '500. Внутренняя ошибка сервера. Корзины для данного пользователя не существует',
    '502 in /cart': '502. Плохой шлюз при загрузке корзины',
    '503 in /cart': '503. Сервис недоступен при загрузке корзины',

    'Error in /user/4': 'Ошибка при загрузке ваших фильмов',
    'Network Error in /user/4': 'Ошибка сети при получении ваших фильмов',
    'Network Error in /user/4. Please try later':
      'Ошибка сети при получении ваших фильмов. Попробуйте снова позже',
    '400 in /user/4': '400. Плохой запрос при загрузке ваших фильмов',
    '401 in /user/4': 'Вы не авторизованны',
    '403 in /user/4': 'У вас нет прав для доступа к данному ресурсу',
    '404 in /user/4': '404. Данный запрос не существует в ваших фильмов',
    '500 in /user/4':
      '500. Внутренняя ошибка сервера. Ваших фильмов для данного пользователя не существует',
    '502 in /user/4': '502. Плохой шлюз при загрузке ваших фильмов',
    '503 in /user/4': '503. Сервис недоступен при загрузке ваших фильмов',
  },
  UserMenu: {
    adminPanel: 'Админ панель',
    profile: 'Профиль',
    orders: 'Мои заказы',
    favorites: 'Избранное',
    feedback: 'Мои отзывы',
    myMovies: 'Мои фильмы',
    signout: 'Выйти',
  },
  AdminPanel: {
    adminPanel: 'Панель администратора',
    enterMovieTitle: 'Введите название фильма',
    enterUserEmail: 'Введите email пользователя',
    addMovie: 'Добавить новый фильм',
    allUsers: 'Все пользователи',
    allMovies: 'Все фильмы',
    siteSettings: 'Настройки сайта',
  },
  mockFavorites: {
    favoritesPage: 'Избранное',
    goBack: 'ВЕРНУТЬСЯ НАЗАД',
  },
  mockOrders: {
    orderPage: 'Мои заказы',
    goBack: 'ВЕРНУТЬСЯ НАЗАД',
  },
  mockProfile: {
    profilePage: 'Профиль',
    goBack: 'ВЕРНУТЬСЯ НАЗАД',
  },
  ModalAddMovieToCart: {
    selectPeriod: 'Выберите период подписки',
    selectFormat: 'Выберите качество фильма',
    submit: 'Подтвердить',
    forever: 'Навсегда',
    'for 7 days': 'На 7 дней',
    'for 30 days': 'На 30 дней',
  },
  UserPage: {
    Profile: 'Профиль',
    Favorites: 'Избранное',
    'Orders list': 'Мои заказы',
    'My feedback': 'Мои отзывы',
    MyMovies: 'Мои фильмы',
    emptyMyMovies: 'У вам нет активных фильмов',
    save: 'Сохранить',
    name: 'имя',
    email: 'эл. почта',
    'date of birth': 'дата рождения',
    goHome: 'ВЕРНУТЬСЯ НА ГЛАВНУЮ',
    empty: 'У вас нет фильмов в избранном!',
    Available: 'Доступно',
    days: 'д',
    hours: 'ч',
    minutes: 'м',
    forever: 'Навсегда',
  },
  MovieControl: {
    tooltipText: 'Данный фильм уже находится в ваших заказах',
  },
  myOrders: {
    orders: 'Мои заказы',
    orderId: 'Номер заказа',
    orderDate: 'Дата заказа',
    filmPrice: 'Стоимость фильма',
    orderPrice: 'Стоимость заказа',
  },
};
